spring.application.name=SpringBoot

spring.datasource.url=jdbc:postgresql://db:5432/forge
spring.datasource.username=postgres
spring.datasource.password=example

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true